packages:
  - products/**/*
  - docs
  - packages/**/*
  - '!**/test/**'

allowBuilds:
  esbuild: true
  vue-demi: true

onlyBuiltDependencies:
  - esbuild
  - vue-demi

patchedDependencies:
  '@figureland/kit@0.0.57': patches/@figureland__kit@0.0.57.patch

allowUnusedPatches: true
